name: Update CONUS Temperature KML

on:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 👉 Check out the gh-pages branch (not main)
      - name: Checkout (gh-pages branch)
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install requests

      - name: Generate KML
        run: python generate_temp_kml.py

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update live CONUS temperature KML"
          branch: gh-pages
          file_pattern: conus_temp_live.kml
